Repository TinkoffCreditSystems/jira-helper, pull requests merged in 2020-09, with the labels that each got.

#63 [#62] Support cube-root power scale for Grid and SLA
  src/charts/utils.js
Labels: bug

#61 [#52] use parameter from settings wip-limit for show sub-task in swimlane bar chart
  src/swimlane/SwimlaneStats.js
Labels: feature

#65 [#64] Fixed Sum issues for personal WIP-limit
  src/column-limits/WIPLimits.js
  src/person-limits/PersonLimits.js
  src/shared/PageModification.js
  src/swimlane/SwimlaneStats.js
Labels: bug

#67 [#66] Show percentage label under SLA line
  src/charts/AddSlaLine.js
Labels: feature

#73 Feature/69
  .travis.yml
  README.md
Labels: enhancement

#76 Read/write SLA value from/to URL, with browser history support
  src/charts/AddSlaLine.js
Labels: feature

#79 [#68] fixed trouble for JIRA 7.1.x
  src/column-limits/WIPLimitsSettings.js
Labels: bug
